# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurpacParser
                                 A QGIS plugin
 Imports data from and exports data to Surpac String File Format
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-12
        copyright            : (C) 2019 by David Gibbons
        email                : david@gibbons.digital
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SurpacParser class from file SurpacParser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .surpac_parser import SurpacParser
    return SurpacParser(iface)
